Monitoring_Server/Monitoring/Controllers/AlertsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace Monitoring.Controllers
{
    public class AlertsController : Controller
    {
        public ActionResult Index()
        {
            using (var dc = new MonitoringDataContext())
            {
                var alerts = dc.Alerts.ToArray();

                return View(alerts);
            }
        }

        [HttpPost]
        public ActionResult Index(Alert[] alerts)
        {
            using (var dc = new MonitoringDataContext())
            {
                foreach (var alert in dc.Alerts)
                {
                    dc.Alerts.DeleteOnSubmit(alert);
                }

                foreach (var alert in alerts)
                {
                    dc.Alerts.InsertOnSubmit(alert);
                }
                dc.SubmitChanges();
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult TriggerAlert()
        {
          // Send Alert - Heart Attack 
            string recipient = WebConfigurationManager.AppSettings["Phone"];
            string eventName = "Heart Rate";
            string body = "Alert: Heart Rate > 100. Emergency Services Contact Number: 615.945.6528";

            
            string server = WebConfigurationManager.AppSettings["SMTPServer"];
            int port = Int32.Parse(WebConfigurationManager.AppSettings["SMTPPort"]);
            string username = WebConfigurationManager.AppSettings["SMTPUser"];
            string password = WebConfigurationManager.AppSettings["SMTPPassword"];

            SmtpClient client = new SmtpClient(server, port)
            {
                Credentials = new NetworkCredential(username, password),
                EnableSsl = true
            };

            MailMessage mailMessage = new MailMessage(username, recipient);
            mailMessage.IsBodyHtml = true;
            mailMessage.Subject = string.Format("Alert for {0}", eventName);
            mailMessage.Body = body;

            client.Send(mailMessage);

            return RedirectToAction("Index", "Home");
        }

    }
}

Monitoring_Server/Monitoring/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Monitoring.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return Content("");
        }

    }
}

Monitoring_Server/Monitoring/Controllers/ReportingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Monitoring.Models;

namespace Monitoring.Controllers
{
    public class ReportingController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("ActivityReport");
        }

        public ActionResult ActivityReport()
        {
            if (Request.IsAjaxRequest())
            {
                using (var dc = new MonitoringDataContext())
                {
                    var fakeData = dc.FakeDatas.Where(x => x.EventDt != null && x.EventDt.Value.Date >= DateTime.Today && x.EventDt.Value < DateTime.Now).OrderBy(x => x.EventDt);

                    var heartRate = fakeData.Where(x => x.Metric == "Heart Rate").Take(100).ToArray();
                    var batteryLife = fakeData.Where(x => x.Metric == "Battery Life").Take(100).ToArray();
                    var activityLevel = fakeData.Where(x => x.Metric == "Activity Level").Take(100).ToArray();


                    var result = new
                    {
                        heartRate = heartRate.Select(r => new
                        {
                            x = ToUtc(r.EventDt.GetValueOrDefault().ToUniversalTime()),
                            y = Convert.ToInt32(r.Value)
                        }).ToArray(),
                        batteryLife = batteryLife.Select(r => new
                        {
                            x = ToUtc(r.EventDt.GetValueOrDefault().ToUniversalTime()),
                            y = Convert.ToInt32(r.Value)
                        }).ToArray(),
                        activityLevel = activityLevel.Select(r => new
                        {
                            x = ToUtc(r.EventDt.GetValueOrDefault().ToUniversalTime()),
                            y = Convert.ToInt32(r.Value)
                        }).ToArray()
                    };



                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            return View();
        }

        public ActionResult AlertReport()
        {
            return View();
        }

        public ActionResult LocationLog()
        {
            return View();
        }

        private long ToUtc(DateTime dt)
        {
            return Convert.ToInt64((DateTime.UtcNow - dt.ToUniversalTime()).TotalMilliseconds);
        }
    }
}

Monitoring_Server/Monitoring/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Monitoring.Controllers
{
    public class SettingsController : Controller
    {

        public ActionResult Index()
        {
            using (var dc = new MonitoringDataContext())
            {
                Setting settings = dc.Settings.FirstOrDefault();

                if (settings == null)
                {
                    settings = new Setting();
                }

                return View(settings);
            }
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
           using (var dc = new MonitoringDataContext())
           {
                Setting settings = dc.Settings.FirstOrDefault();
                if (settings == null)
                {
                    settings = new Setting();
                    dc.Settings.InsertOnSubmit(settings);
                }

                UpdateModel(settings);

                dc.SubmitChanges();
           }

            return RedirectToAction("Index", "Alerts");

        }
    }
}

Monitoring_Server/Monitoring/Views/Shared/_Home.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    

</head>
    <body>


        
        @RenderBody()
    
    
    
    
    
    

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="@Url.Content("~/Content/dashboard.css")">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
        @RenderSection("scripts", required: false)
    
    
        <style type="text/css">
            body {
                text-align: center;
                overflow: hidden;
            }

            .form-horizontal .control-label {
                margin-bottom: 0;
                padding-top: 7px;
                padding-left: 20px;
                padding-right: 10px;
                text-align: left;
            }
        </style>
    

    </body>
</html>

Monitoring_Server/Monitoring/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    

</head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")">iScry</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("Index", "Settings")">Settings</a></li>
                        <li><a href="@Url.Action("Index", "Alerts")">Alerts</a></li>
                        <li><a href="@Url.Action("Index", "Reporting")">Reports</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        
        @RenderBody()
    
    
    
    
    
    

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="@Url.Content("~/Content/dashboard.css")">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
        @RenderSection("scripts", required: false)
    
    
        <style type="text/css">
            body {
                text-align: center;
                overflow: hidden;
            }

            .form-horizontal .control-label {
                margin-bottom: 0;
                padding-top: 7px;
                padding-left: 20px;
                padding-right: 10px;
                text-align: left;
            }
        </style>
    

    </body>
</html>

Monitoring_Server/Monitoring/Views/Shared/_Live.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()
    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="@Url.Content("~/Content/dashboard.css")">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>